# Generated by Django 4.1.1 on 2023-07-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_myform_delete_musicians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myform',
            name='song_link',
            field=models.URLField(verbose_name='song_link'),
        ),
    ]
