# Generated by Django 4.1.1 on 2023-07-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_myform_song_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='myform',
            name='image',
            field=models.TextField(default='', null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='myform',
            name='video',
            field=models.URLField(null=True, verbose_name='video'),
        ),
    ]
