# Generated by Django 4.1.1 on 2023-07-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_myform_image_myform_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='myform',
            name='person_data',
            field=models.CharField(max_length=250, null=True, verbose_name='person_data'),
        ),
    ]
